### ISSUE TITLE
Algunos archivos de la carpeta .idea deben ser autogenerados

### ISSUE THREAD

**Issue by jlmanrique** [eknowit/Android-Studio-Ejemplos#1]
Los archivos de la carpeta .idea contienen información del proyecto y también información propia de la maquina en la que fue creada el proyecto, lo ideal sería ignorar aquellos que poseen la dependencia de la maquina y mantener aquellos que forman parte del proyecto. En este [link](http://stackoverflow.com/questions/26336709/android-studio-should-the-entire-idea-directory-be-in-git-ignore) puedes ver algunas ideas.

**Comment by marti1125** [comment]
uhmm he visto algunos archivos del .idea no lo veo nada raro... el proyecto ya tiene su gitignore
https://github.com/eknowit/Android-Studio-Ejemplos/blob/master/Reminders/.gitignore

**Comment by marti1125** [comment]
se retiro el archivo gradle.xml que hacia referencia al gradleHome" value="G:\android-studio\gradle\gradle-2.2.1" />
